### ISSUE TITLE
Customize transition error "reason"

### ISSUE THREAD

**Issue by wfgilman** [joaomdmoura/machinery#34]
I have some complex guard conditions and I'd like to take specific action depending on which one fails. I'd love to see support for returning a customized "reason" in the `{:error, "reason"}` tuple when `transition_to/3` fails.

For example, if I have five guard conditions that need to be met in order to make a user `active`, I'd like to pattern match on the reason for failure to transition the user to a new state.

Love this library 👍

**Comment by joaomdmoura** [comment]
@wfgilman Thanks for opening up the issue, indeed it seems like a great use case. 
Btw right now we only allow one guard condition per transition.

Right now we only expect guard functions to return a `boolean`, but I guess we could make it a tuple `{:ok, "reason"}` or `{:error, "reason"}` instead of `true or false`, and that could be properly propagated.

Thanks again for opening the issue! :smile:  make yourself comfortable to suggest new features/fixes or share more about how you have been using it online.

**Comment by wfgilman** [comment]
Although the guard returns a Boolean, most of my conditions chain multiple Boolean expressions together to determine whether the guard passes. 

Your suggestion is along the lines of what I was thinking!

**Comment by joaomdmoura** [comment]
@wfgilman I have a PR open that tackle this, can you check it? https://github.com/joaomdmoura/machinery/pull/35

**Comment by joaomdmoura** [comment]
@wfgilman now available in version `0.16`

**Comment by wfgilman** [comment]
👍
