### ISSUE TITLE
Question: Do you always need a process to be a state machine?

### ISSUE THREAD

**Issue by themitigater** [joaomdmoura/machinery#57]
Hey,
I would like to understand what exactly do you mean by "Do you always need a process to be a state machine?", I've just recently started with elixir and am exploring ruby like state-machine implementation.

Thanks in advance.

**Comment by edisonywh** [comment]
I am also confused by the wording, would love some clarification!

**Comment by joaomdmoura** [comment]
Hey folks, basically `machinery` has an approach more focused on web applications and applications with clear database resources and such.
But there are people building different systems with Elixir, more different than the usual structure we are used to in the web, in some cases they are working more around the concepts of have processes as state machines instead of thinking in terms of resources and a database to store that. For those cases that are older tools in the OTP already that tackle this very well.
